INSERT INTO "GardenManager".pest (pestname,"Type",description,"control") VALUES
	 ('Aphids','Insect','Very small insects ranging in colour from green, pinkish to black. Young aphids are wingless; adults can be winged or wingless. Aphids cluster on stems and/or undersides of leaves.','Biological controls like lacewing, ladybird beetles and ants are effective. Sticky traps are useful to catch winged aphids, as is insecticidal soap.'),
	 ('Cabbage aphid','Insect','Very small insects ranging in colour from green, pinkish to black. Young aphids are wingless; adults can be winged or wingless. Aphids cluster on stems and/or undersides of leaves.','Biological controls like lacewing, ladybird beetles and ants are effective. Sticky traps are useful to catch winged aphids, as is insecticidal soap.'),
	 ('Cabbage moth','Insect','Larvae are light green, 1 cm long, with white stripe along each side of the body. They often feed at the base of developing cabbage heads inside the leaves.','Pheromone traps are effective, as are biological methods like flies and wasps.'),
	 ('Fusarium wilt','Fungus','Fungus that affects both seedlings and mature plants. It causes the top growth to wilt, yellow and die. Lesions form at plant base or slightly below the soil line.','Remove and destroy infected plants; grow resistant varieties; raise the pH to 6.5-7 if soil is acidic. Microbial seed treatments are available and effective.'),
	 ('Leafminer','Insect','Larvae burrow underneath leaf surfaces leaving a visible trail as they eat their way through the leaf. Leafminers can be flies, wasps, moths, or sawflies.','Biological controls like parasitic wasps are effective; neem oil is effective if applied early.'),
	 ('Mosaic virus','Virus','Causes characteristic "mosaic" colouring in affected plants. Leaves are mottled with yellow, white, and light or dark green spots and streaks; plants are often stunted. Affects a wide variety of plants.','There is no cure, although virus-resistant varieties of many species exist. Remove all affected plants and destroy them -- virus persists in infected plant matter.'),
	 ('Rust','Fungus','Early symptoms are white, slightly raised spots on the underside of leaves that progress into larger reddish-brown spots.','Remove infected leaves and surrounding debris; fungicide is effective.'),
	 ('Scab','Fungus','Appears as a corky or crustaceous lesion on the surface of fruits, tubers, leaves or stems, and may be mistaken for insect damage.','Fungicide application is effective.'),
	 ('Slug','Animal','Slugs feed on many types of plants, but prefer tender young seedlings. Slug damage can look like round holes in soft fruits like strawberries and tomatoes, or like irregularily shaped holes in leaves.','Can be removed by hand (best done at night since they are nocturnal feeders).'),
	 ('Smut','Fungus','Causes swelling in aboveground plant tissues. Plant cells become spongy-gray, then black as the spores mature.','There is no control; remove and destroy all infected plants.');
INSERT INTO "GardenManager".pest (pestname,"Type",description,"control") VALUES
	 ('Powdery mildew','Fungus','Plants infected with powdery mildew look as if they have been dusted with white powder, especially on the upper sides of leaves. Leaves may turn yellow and die.','Fungicides are effective for mild to moderate infection, but for severe cases the best method of control is to remove and destroy infected plants.');