INSERT INTO "GardenManager".species (genus,species,commonname,lifecycle) VALUES
	 ('Solanum                       ','lycopersicum                  ','Tomato                                  ','Annual    '),
	 ('Convallaria                   ','majalis                       ','Lily-of-the-Valley                      ','Perennial '),
	 ('Lavendula                     ','angustifolia                  ','Lavender                                ','Perennial '),
	 ('Lactuca                       ','sativa                        ','Lettuce                                 ','Annual    '),
	 ('Cucumis                       ','sativa                        ','Cucumber                                ','Annual    '),
	 ('Pisum                         ','sativum                       ','Pea                                     ','Annual    '),
	 ('Phaseolus                     ','vulgaris                      ','Bean                                    ','Annual    '),
	 ('Daucus                        ','carota                        ','Carrot                                  ','Biennial  '),
	 ('Allium                        ','sativum                       ','Garlic                                  ','Annual    '),
	 ('Allium                        ','cepa                          ','Onion                                   ','Annual    ');
INSERT INTO "GardenManager".species (genus,species,commonname,lifecycle) VALUES
	 ('Fragaria                      ','vesca                         ','Strawberry                              ','Perennial '),
	 ('Beta                          ','vulgaris                      ','Beet                                    ','Annual    '),
	 ('Capsicum                      ','annuum                        ','Capsicum                                ','Annual    '),
	 ('Rheum                         ','rhabarbarum                   ','Rhubarb                                 ','Perennial '),
	 ('Brassica                      ','oleracea                      ','Cabbage                                 ','Annual    '),
	 ('Zea                           ','mays                          ','Corn                                    ','Annual    '),
	 ('Spinacia                      ','oleracea                      ','Spinach                                 ','Annual    '),
	 ('Mentha                        ','spicata                       ','Spearmint                               ','Perennial '),
	 ('Metha                         ','x piperata                    ','Peppermint                              ','Perennial ');